// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByS3p67sd1mL79Ez5WYlO4sLUMVTKak5M',
    appId: '1:481043901341:web:5bd2d5b97aaeb3e86f1d74',
    messagingSenderId: '481043901341',
    projectId: 'fruit-hub-18327',
    authDomain: 'fruit-hub-18327.firebaseapp.com',
    storageBucket: 'fruit-hub-18327.firebasestorage.app',
    measurementId: 'G-6EBBEHJ1C1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrDZpnx-RV0Z7iPq7Xhij8zYQG87EE4iw',
    appId: '1:481043901341:android:9a0e648184d9fa196f1d74',
    messagingSenderId: '481043901341',
    projectId: 'fruit-hub-18327',
    storageBucket: 'fruit-hub-18327.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9KJsKql0duIZ7ZwhpERkJdgp2co9DzNw',
    appId: '1:481043901341:ios:c7a256cdbf9e4f6d6f1d74',
    messagingSenderId: '481043901341',
    projectId: 'fruit-hub-18327',
    storageBucket: 'fruit-hub-18327.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9KJsKql0duIZ7ZwhpERkJdgp2co9DzNw',
    appId: '1:481043901341:ios:c7a256cdbf9e4f6d6f1d74',
    messagingSenderId: '481043901341',
    projectId: 'fruit-hub-18327',
    storageBucket: 'fruit-hub-18327.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByS3p67sd1mL79Ez5WYlO4sLUMVTKak5M',
    appId: '1:481043901341:web:05f38a6dcfc586956f1d74',
    messagingSenderId: '481043901341',
    projectId: 'fruit-hub-18327',
    authDomain: 'fruit-hub-18327.firebaseapp.com',
    storageBucket: 'fruit-hub-18327.firebasestorage.app',
    measurementId: 'G-YWGY720GYD',
  );
}
